# Generated by Django 3.2.9 on 2022-01-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activelistings',
            name='price',
            field=models.FloatField(blank=True, max_length=60, null=True, verbose_name='Початкова ставка, $'),
        ),
        migrations.AlterField(
            model_name='activelistings',
            name='start_bet',
            field=models.FloatField(blank=True, max_length=60, null=True, verbose_name='Ставка, $'),
        ),
    ]
