# Generated by Django 3.2.9 on 2022-01-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20220125_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='bet_price',
            field=models.FloatField(max_length=60, null=True, verbose_name='Ставка, $'),
        ),
    ]
