# Generated by Django 3.2.9 on 2022-02-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_bet_bet_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activelistings',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True, verbose_name='Початкова ставка, $'),
        ),
        migrations.AlterField(
            model_name='activelistings',
            name='start_bet',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True, verbose_name='Ставка, $'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='bet_price',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='Ставка, $'),
        ),
    ]
