# Generated by Django 3.2.9 on 2022-02-03 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20220202_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='activelistings',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Закрити аукціон'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='title',
            field=models.CharField(default='Заголовок', max_length=150, verbose_name='Заголовок'),
        ),
    ]
