# Generated by Django 3.2.9 on 2022-02-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20220203_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='activelistings',
            name='winner',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Переможець'),
        ),
    ]
